# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1cac61b211bb1f33ba6d6162c1010c5f37c2153ac9aa9d7c8fa18f006d5c3cbe1e49d192c53274fa941bb547e6d4c49474ab8264a202a835e21179ece02cd143

test:
  secret_key_base: 1f0569c7cf39d90445a9accb11a8c64cc8ac3223bc00e72fde3b5e00b637aac3398d834440958f40a74559a3fa9e2dcc52ab761e979026052c3a1b3decf320ed

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
